// Illustrative catalogue: replace with confirmed prices before accepting payments.
const sizes=[{ml:'8OZ',price:5},{ml:'12OZ',price:8},{ml:'1L',price:14}],lines=[];let selectedSize=0;
let selectedFlavour=0;
const cash=n=>'CAD $'+n.toFixed(2);
const popup=document.createElement('dialog');popup.id='bottle-options';popup.setAttribute('aria-labelledby','option-title');popup.innerHTML=`<button id="close-options" aria-label="Close bottle options">×</button><div class="option-art"><img src="assets/bottle.webp" alt="Zobo Oh! sample bottle"></div><h2 id="option-title"></h2><fieldset class="size-options"><legend>Bottle size</legend><div class="size-pills"><label><input type="radio" name="bottle-size" value="0" checked><span>8OZ BOTTLE</span></label><label><input type="radio" name="bottle-size" value="1"><span>12OZ BOTTLE</span></label><label><input type="radio" name="bottle-size" value="2"><span>1L BOTTLE</span></label></div></fieldset><label>Number of bottles<input id="option-quantity" type="number" min="1" max="50" value="1"></label><label>Sweetness <output id="option-sweetness-label">3 / 5</output><input id="option-sweetness" type="range" min="1" max="5" value="3"></label><div class="sweetness-ends"><span>Lightly sweet</span><span>Extra sweet</span></div><div class="option-total">Estimated total <strong id="option-total"></strong></div><p class="option-note">Illustrative demo prices in CAD. Taxes and delivery are not included.</p><details><summary>Terms &amp; conditions</summary><p>Demo terms for review: sizes, flavours and prices are provisional. This preview does not place orders or accept payment. Final delivery, cancellation, refund and privacy terms must be confirmed before checkout launches. Review the allergy information before ordering.</p></details><button class="button" id="option-add">Add to cart +</button>`;document.body.append(popup);
function estimate(){const quantity=Math.max(1,Math.min(50,Math.floor(Number($('option-quantity').value)||1)));$('option-quantity').value=quantity;const size=sizes[Number($('option-size').value)];$('option-total').textContent=cash(quantity*size.price);$('option-sweetness-label').textContent=$('option-sweetness').value+' / 5';return {quantity,size}}
$('expressive-add').onclick=()=>{selectedFlavour=current;$('option-title').textContent=flavours[current].label;popup.style.setProperty('--option-color',flavours[current].color);$('option-quantity').value=1;$('option-sweetness').value=3;estimate();popup.showModal()};$('close-options').onclick=()=>popup.close();['option-quantity','option-sweetness'].forEach(id=>$(id).oninput=estimate);
const subtotal=document.createElement('div');subtotal.className='option-total';$('bag-items').after(subtotal);const checkout=document.createElement('button');checkout.className='button';checkout.textContent='Continue to checkout ↗';subtotal.after(checkout);const notice=document.createElement('p');notice.className='option-note';notice.setAttribute('role','status');checkout.after(notice);checkout.onclick=()=>notice.textContent='Checkout preview: secure online payment will be connected after pricing, delivery and terms are confirmed. No payment has been taken.';
renderBag=function(){const total=lines.reduce((sum,l)=>sum+l.quantity,0);$('bag-count').textContent=total;$('open-bag').setAttribute('aria-label',`Open bag, ${total} bottles`);$('bag-items').replaceChildren();if(!total)$('bag-items').textContent='Your cart is waiting for something good.';lines.forEach((line,index)=>{const row=document.createElement('div');row.className='configured-line';const title=document.createElement('strong');title.textContent=flavours[line.flavour].label;const detail=document.createElement('p');detail.textContent=`${line.ml} · Sweetness ${line.sweetness}/5 · ${cash(line.price)} each`;const controls=document.createElement('div');controls.className='quantity-controls';[-1,1].forEach(delta=>{const b=document.createElement('button');b.textContent=delta<0?'−':'+';b.setAttribute('aria-label',`${delta<0?'Remove':'Add'} one ${flavours[line.flavour].label}, ${line.ml}, sweetness ${line.sweetness}`);b.onclick=()=>{line.quantity+=delta;if(!line.quantity)lines.splice(index,1);renderBag()};controls.append(b);if(delta<0){const n=document.createElement('span');n.textContent=line.quantity;controls.append(n)}});row.append(title,detail,controls);$('bag-items').append(row)});subtotal.textContent='Estimated subtotal: '+cash(lines.reduce((sum,l)=>sum+l.quantity*l.price,0));checkout.disabled=!total};
$('option-add').onclick=()=>{const {quantity,size}=estimate(),sweetness=Number($('option-sweetness').value);const existing=lines.find(l=>l.flavour===selectedFlavour&&l.ml===size.ml&&l.sweetness===sweetness);if(existing)existing.quantity+=quantity;else lines.push({flavour:selectedFlavour,ml:size.ml,price:size.price,sweetness,quantity});renderBag();popup.close();openBag()};$('footer-order').textContent='Your cart';renderBag();
 popup.querySelectorAll('input[name=bottle-size]').forEach(input=>input.onchange=()=>{selectedSize=Number(input.value);estimate()});