// Illustrative catalogue: replace with confirmed prices before accepting payments.
const sizes=[{ml:'8OZ',price:5},{ml:'12OZ',price:8},{ml:'1L',price:14}],lines=[];let selectedSize=0;
let selectedFlavour=0;
const cash=n=>'CAD $'+n.toFixed(2);
const popup=document.createElement('dialog');popup.id='bottle-options';popup.setAttribute('aria-labelledby','option-title');popup.innerHTML=`<button id="close-options" aria-label="Close bottle options">×</button><div class="option-art"><img src="assets/bottle.webp" alt="Zobo Oh! sample bottle"></div><h2 id="option-title"></h2><fieldset class="size-options"><legend>Bottle size</legend><div class="size-pills"><label><input type="radio" name="bottle-size" value="0" checked><span>8OZ BOTTLE</span></label><label><input type="radio" name="bottle-size" value="1"><span>12OZ BOTTLE</span></label><label><input type="radio" name="bottle-size" value="2"><span>1L BOTTLE</span></label></div></fieldset><div class="bottle-quantity"><span id="quantity-label">Number of bottles</span><div class="bottle-stepper" role="group" aria-labelledby="quantity-label"><button type="button" id="quantity-minus" aria-label="Decrease bottle quantity">−</button><output id="quantity-display" aria-live="polite">1</output><button type="button" id="quantity-plus" aria-label="Increase bottle quantity">+</button></div><input id="option-quantity" type="hidden" value="1"></div><label>Sweetness <output id="option-sweetness-label">3 / 5</output><input id="option-sweetness" type="range" min="1" max="5" value="3"></label><div class="sweetness-ends"><span>Lightly sweet</span><span>Extra sweet</span></div><div class="option-total">Estimated total <strong id="option-total"></strong></div><p class="option-note">Illustrative demo prices in CAD. Taxes and delivery are not included.</p><details><summary>Terms &amp; conditions</summary><p>Demo terms for review: sizes, flavours and prices are provisional. This preview does not place orders or accept payment. Final delivery, cancellation, refund and privacy terms must be confirmed before checkout launches. Review the allergy information before ordering.</p></details><button class="button" id="option-add">Add to cart +</button>`;document.body.append(popup);
function estimate(){const quantity=Math.max(1,Math.min(50,Math.floor(Number($('option-quantity').value)||1)));$('option-quantity').value=quantity;const size=sizes[selectedSize];$('option-total').textContent=cash(quantity*size.price);$('option-sweetness-label').textContent=$('option-sweetness').value+' / 5';$('quantity-display').textContent=quantity;$('quantity-minus').disabled=quantity<=1;$('quantity-plus').disabled=quantity>=50;return {quantity,size}}
$('expressive-add').onclick=()=>{selectedFlavour=current;$('option-title').textContent=flavours[current].label;popup.style.setProperty('--option-color',flavours[current].color);$('option-quantity').value=1;$('option-sweetness').value=3;estimate();popup.showModal()};$('close-options').onclick=()=>popup.close();['option-quantity','option-sweetness'].forEach(id=>$(id).oninput=estimate);
const subtotal=document.createElement('div');subtotal.className='option-total';$('bag-items').after(subtotal);const checkout=document.createElement('button');checkout.className='button';checkout.textContent='Continue to checkout ↗';subtotal.after(checkout);const notice=document.createElement('p');notice.className='option-note';notice.setAttribute('role','status');checkout.after(notice);checkout.onclick=()=>notice.textContent='Checkout preview: secure online payment will be connected after pricing, delivery and terms are confirmed. No payment has been taken.';
renderBag=function(){const total=lines.reduce((sum,l)=>sum+l.quantity,0);$('bag-count').textContent=total;$('open-bag').setAttribute('aria-label',`Open bag, ${total} bottles`);$('bag-items').replaceChildren();if(!total)$('bag-items').textContent='Your cart is waiting for something good.';lines.forEach((line,index)=>{const row=document.createElement('div');row.className='configured-line';const title=document.createElement('strong');title.textContent=flavours[line.flavour].label;const detail=document.createElement('p');detail.textContent=`${line.ml} · Sweetness ${line.sweetness}/5 · ${cash(line.price)} each`;const controls=document.createElement('div');controls.className='quantity-controls';[-1,1].forEach(delta=>{const b=document.createElement('button');b.textContent=delta<0?'−':'+';b.setAttribute('aria-label',`${delta<0?'Remove':'Add'} one ${flavours[line.flavour].label}, ${line.ml}, sweetness ${line.sweetness}`);b.onclick=()=>{line.quantity+=delta;if(!line.quantity)lines.splice(index,1);renderBag()};controls.append(b);if(delta<0){const n=document.createElement('span');n.textContent=line.quantity;controls.append(n)}});const artwork=document.createElement("div");artwork.className="cart-item-art";artwork.style.background=flavours[line.flavour].color;const image=document.createElement("img");image.src="assets/bottle.webp";image.alt="";artwork.append(image);const content=document.createElement("div");content.className="cart-item-content";const lineTotal=document.createElement("strong");lineTotal.className="cart-line-total";lineTotal.textContent=cash(line.quantity*line.price);content.append(title,detail,controls,lineTotal);row.append(artwork,content);$('bag-items').append(row)});subtotal.textContent='Estimated subtotal: '+cash(lines.reduce((sum,l)=>sum+l.quantity*l.price,0));checkout.disabled=!total};
$('option-add').onclick=()=>{const {quantity,size}=estimate(),sweetness=Number($('option-sweetness').value);const existing=lines.find(l=>l.flavour===selectedFlavour&&l.ml===size.ml&&l.sweetness===sweetness);if(existing)existing.quantity+=quantity;else lines.push({flavour:selectedFlavour,ml:size.ml,price:size.price,sweetness,quantity});renderBag();animateAddToBag()};$('footer-order').textContent='Your cart';renderBag();
 popup.querySelectorAll('input[name=bottle-size]').forEach(input=>input.onchange=()=>{selectedSize=Number(input.value);estimate()});['quantity-minus','quantity-plus'].forEach((id,index)=>$(id).onclick=()=>{$('option-quantity').value=Number($('option-quantity').value)+(index?1:-1);estimate()});
// Keep the two actions distinct: add flies to the bag; checkout opens the cart.
const optionCheckout=document.createElement('button');optionCheckout.id='option-checkout';optionCheckout.className='text-link';optionCheckout.textContent='Check out ↗';$('option-add').after(optionCheckout);
const addFeedback=document.createElement('p');addFeedback.setAttribute('role','status');addFeedback.className='add-feedback';document.body.append(addFeedback);
let cartAnimating=false;
async function animateAddToBag(){
 if(cartAnimating)return;cartAnimating=true;$('option-add').disabled=true;optionCheckout.disabled=true;
 const rect=popup.getBoundingClientRect(),color=["#a5345c","#b4770c","#b93667"][selectedFlavour],cx=rect.left+rect.width/2,cy=rect.top+rect.height/2;
 const circle=document.createElement('div');circle.className='cart-flight';circle.style.background=color;circle.style.left=(cx-24)+'px';circle.style.top=(cy-24)+'px';
 const originalStyle=popup.getAttribute('style');const animations=[];
 try{
 if(!reduced){
 Object.assign(popup.style,{position:'fixed',margin:'0',left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px',minHeight:'0',maxHeight:'none',boxSizing:'border-box',overflow:'hidden'});
 [...popup.children].forEach(child=>animations.push(child.animate([{opacity:1,filter:'blur(0px)'},{opacity:0,filter:'blur(14px)'}],{duration:420,easing:'ease-in',fill:'forwards'})));
 const morph=popup.animate([{left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px',padding:'30px',borderRadius:'24px',background:getComputedStyle(popup).backgroundColor},{left:(cx-24)+'px',top:(cy-24)+'px',width:'48px',height:'48px',padding:'0px',borderRadius:'50%',background:color}],{duration:650,easing:'cubic-bezier(.4,0,.2,1)',fill:'forwards'});animations.push(morph);await morph.finished;
 await new Promise(resolve=>setTimeout(resolve,220));
 }
 document.body.append(circle);popup.close();animations.forEach(a=>a.cancel());if(originalStyle===null)popup.removeAttribute('style');else popup.setAttribute('style',originalStyle);
 if(!reduced){
 const target=document.querySelector('.bag-icon').getBoundingClientRect(),dx=target.left+target.width/2-cx,dy=target.top+target.height/2-cy;
 const flight=circle.animate([{transform:'translate(0,0) scale(1)',opacity:1},{transform:'translate('+dx*.55+'px,'+(dy*.55-45)+'px) scale(.85)',opacity:1,offset:.55},{transform:'translate('+dx+'px,'+dy+'px) scale(.15)',opacity:0}],{duration:700,easing:'cubic-bezier(.4,0,.25,1)',fill:'forwards'});await flight.finished;
 await $('open-bag').animate([{transform:'scale(1)'},{transform:'scale(1.16) rotate(-5deg)',offset:.4},{transform:'scale(1)'}],{duration:350}).finished;
 }
 addFeedback.textContent=flavours[selectedFlavour].label+' added to your cart.';setTimeout(()=>addFeedback.textContent='',3200);
 }finally{circle.remove();animations.forEach(a=>a.cancel());if(originalStyle===null)popup.removeAttribute('style');else popup.setAttribute('style',originalStyle);cartAnimating=false;$('option-add').disabled=false;optionCheckout.disabled=false}
}
optionCheckout.onclick=async()=>{
 if(cartAnimating)return;cartAnimating=true;optionCheckout.disabled=true;
 try{if(!reduced)await popup.animate([{transform:'translateX(0)',opacity:1},{transform:'translateX(-80px)',opacity:0}],{duration:230,easing:'ease-in'}).finished;popup.close();openBag();if(!reduced)await $('bag-dialog').animate([{transform:'translateX(80px)',opacity:0},{transform:'translateX(0)',opacity:1}],{duration:380,easing:'ease-out'}).finished;}
 finally{cartAnimating=false;optionCheckout.disabled=false}
};
const stickyNav=document.querySelector('header');function updateStickyNav(){stickyNav.classList.toggle('is-scrolled',scrollY>30)}addEventListener('scroll',updateStickyNav,{passive:true});updateStickyNav();
