const flavourSection=document.querySelector('.flavours');
const flavourPanel=$('flavour-panel');
const movingParts=[flavourPanel.querySelector('.flavour-copy'),flavourPanel.querySelector('.flavour-visual')];
const colourReveal=document.createElement('div');colourReveal.className='flavour-colour-reveal';colourReveal.setAttribute('aria-hidden','true');flavourSection.prepend(colourReveal);
const edgeButtons=['previous','next'].map((direction)=>{const button=document.createElement('button');button.className=`flavour-peek flavour-peek-${direction}`;button.innerHTML='<span aria-hidden="true">'+(direction==='previous'?'←':'→')+'</span>';flavourSection.append(button);button.onclick=()=>selectFlavour(current+(direction==='next'?1:-1),false,direction==='next'?1:-1);return button});
let transitionBusy=false,queuedFlavour=null;
function updateFlavour(index,paint=true){current=index;const f=flavours[current];if(paint)flavourSection.style.setProperty('--scene',f.color);$('flavour-name').innerHTML=`${f.name}<br><i>${f.ending}</i>`;$('flavour-description').textContent=f.description;$('flavour-eyebrow').textContent=f.eyebrow;$('flavour-ingredients').innerHTML=f.ingredients.map(n=>`<span>${n}</span>`).join('');$('flavour-count').textContent=`0${current+1} / 03`;$('flavour-bottle').alt=`Zobo Oh! sample bottle — ${f.label} concept`;flavourPanel.setAttribute('aria-labelledby',`tab-${current}`);document.querySelectorAll('[data-flavour]').forEach((tab,i)=>{tab.setAttribute('aria-selected',String(i===current));tab.tabIndex=i===current?0:-1});edgeButtons.forEach((button,i)=>{const neighbour=flavours[(current+(i===0?-1:1)+flavours.length)%flavours.length];button.style.background=neighbour.color;button.setAttribute('aria-label',`${i===0?'Previous':'Next'} flavour: ${neighbour.label}`)});}
async function selectFlavour(index,focus=false,direction){const target=(index+flavours.length)%flavours.length;if(transitionBusy){queuedFlavour={target,focus,direction};return}if(target===current)return;const sign=direction??(target>current?1:-1);if(focus)$(`tab-${target}`).focus();if(reduced){updateFlavour(target);return}transitionBusy=true;flavourSection.classList.add('flavour-moving');$('expressive-add').disabled=true;
colourReveal.style.background=flavours[target].color;colourReveal.style.transformOrigin=sign===1?'right center':'left center';const wipe=colourReveal.animate([{transform:'scaleX(0)',opacity:1},{transform:'scaleX(1)',opacity:1}],{duration:640,easing:'cubic-bezier(.65,0,.25,1)',fill:'forwards'});
try{await Promise.all(movingParts.map((part,i)=>part.animate([{transform:'translateX(0)',opacity:1},{transform:`translateX(${-sign*(i?100:70)}px)`,opacity:0}],{duration:250,easing:'ease-in',fill:'forwards'}).finished));updateFlavour(target,false);await Promise.all(movingParts.map((part,i)=>{part.getAnimations().forEach(a=>a.cancel());return part.animate([{transform:`translateX(${sign*(i?140:90)}px)`,opacity:0},{transform:'translateX(0)',opacity:1}],{duration:480,easing:'cubic-bezier(.2,.8,.2,1)',fill:'forwards'}).finished}));await wipe.finished;flavourSection.style.setProperty('--scene',flavours[target].color);}finally{movingParts.forEach(p=>p.getAnimations().forEach(a=>a.cancel()));wipe.cancel();flavourSection.classList.remove('flavour-moving');$('expressive-add').disabled=false;transitionBusy=false;const next=queuedFlavour;queuedFlavour=null;if(next)selectFlavour(next.target,next.focus,next.direction)}}
document.querySelectorAll('[data-flavour]').forEach(tab=>{tab.onclick=()=>selectFlavour(Number(tab.dataset.flavour));tab.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();selectFlavour(e.key==='Home'?0:e.key==='End'?2:current+(e.key==='ArrowRight'?1:-1),true,e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:undefined)}}});$('next-flavour').onclick=()=>selectFlavour(current+1,false,1);$('previous-flavour').onclick=()=>selectFlavour(current-1,false,-1);
let expressiveTimer;$('expressive-add').onclick=()=>{bag[current]++;renderBag();$('expressive-add').innerHTML='Added. Good choice! <span>✓</span>';clearTimeout(expressiveTimer);expressiveTimer=setTimeout(()=>$('expressive-add').innerHTML='Add to your bag <span>+</span>',1400)};
let flavourTouch=null;flavourPanel.style.touchAction='pan-y';flavourPanel.addEventListener('touchstart',e=>flavourTouch={x:e.touches[0].clientX,y:e.touches[0].clientY},{passive:true});flavourPanel.addEventListener('touchend',e=>{if(!flavourTouch)return;const dx=e.changedTouches[0].clientX-flavourTouch.x,dy=e.changedTouches[0].clientY-flavourTouch.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.3)selectFlavour(current+(dx<0?1:-1),false,dx<0?1:-1);flavourTouch=null},{passive:true});flavourPanel.addEventListener('touchcancel',()=>flavourTouch=null,{passive:true});updateFlavour(current);
